import json
from google import genai
from google.genai import types
import os
from dotenv import load_dotenv 
import time


# Load environment variables
load_dotenv()
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

if not GOOGLE_API_KEY:
    raise SystemExit("GOOGLE_API_KEY not set in environment!")

# Initialize client
client = genai.Client()

# https://ai.google.dev/gemini-api/docs/rate-limits
requests_per_minute = 10
tokens_per_minute = 250000
requests_per_day = 250
ideal_tokens_per_request = tokens_per_minute / requests_per_minute


# Enable Google Search tool
grounding_tool = types.Tool(
    google_search=types.GoogleSearch()
)

# Configure generation with the grounding tool
config = types.GenerateContentConfig(
    tools=[grounding_tool]
)


def add_citations_at_end(response):
    text = response.text
    supports = response.candidates[0].grounding_metadata.grounding_supports
    chunks = response.candidates[0].grounding_metadata.grounding_chunks
    
    # Dictionary to hold unique citations {chunk_index: (uri, title)}
    citation_dict = {}
    
    for support in supports:
        for i in support.grounding_chunk_indices:
            if i < len(chunks):
                uri = chunks[i].web.uri
                title = chunks[i].web.title if hasattr(chunks[i].web, 'title') else uri
                citation_dict[i] = (uri, title)
    
    # Sort citation indices
    sorted_indices = sorted(citation_dict.keys())
    
    if sorted_indices:
        citations_text = "\n\nReference Urls:\n"
        for idx, chunk_index in enumerate(sorted_indices, start=1):
            uri, title = citation_dict[chunk_index]
            citations_text += f"[{idx}] {title} - {uri}\n"
        text += citations_text
    
    return text

TECH_GROUPS = [
 "Storage Adapters", "Storage Accessories", "Read-Only Memory", "VPN gateway", "Antivirus",
 "10/100 Hubs & Switches", "10/25/40/50/100 Gigabit Switches", "35mm Camera Lenses",
 "3D Cameras", "3D Design", "3D Printers", "3D Scanners",
 "3G Phones",
 "4G Phones",
 "5G Phones",
 "Accounting",
 "Action Cameras",
 "All-In-One Desktops",
 "AMD Desktops",
 "AMD Notebooks",
 "AMD Video Cards",
 "Amplifiers",
 "Analog Camcorders",
 "Animation",
 "Answering Machines",
 "Apple Desktops",
 "Apple Notebooks",
 "Apple Servers",
 "APS Cameras",
 "Arts & Culture",
 "Assorted Accessories",
 "ATM Cards",
 "ATX Cases",
 "Audio & Video",
 "Audio & Video Equipment Mounts",
 "Audio & Video Switches",
 "Audio Cables",
 "AV Blank Media",
 "AV Receivers",
 "B&W Multifunction Laser Printers",
 "Backgrounds",
 "Banknote Counters",
 "Banknotes/Coins Wrappers",
 "Barcode Scanners",
 "Barebone Systems",
 "Blackberry",
 "Blade Servers",
 "Blu-ray Media",
 "Blu-ray Players",
 "Bluetooth Adapters",
 "Bluetooth Keyboards",
 "Bluetooth Print Servers",
 "Boomboxes",
"Browsers",
"Built-in Car Navigation",
"Bulk Network Cables",
"Business / Economics / Legal",
"Business & Productivity Software",
"Business Notebooks",
"Cable Modems",
"Cabling Accessories",
"CAD/CAM Software",
"Caller ID",
"Camcorder Accessories & Accessory Kits",
"Camcorder Batteries",
"Camcorder Cases",
"Camcorder Cleaning",
"Camcorder Lenses",
"Camcorder Media",
"Camcorder Tripods",
"Camcorders Lens Filters",
"Camera Accessories & Accessory Kits",
"Camera Batteries",
"Camera Cases",
"Camera Cleaning",
"Camera Drones",
"Camera Drones Accessories",
"Camera Lens Filters",
"Camera Tripods",
"Car Accessories",
"Car Amplifiers & Equalizers",
"Car Audio & Video Cables",
"Car Audio Amplifiers",
"Car Audio Crossovers",
"Car Cassette Player",
"Car CD Changers",
"Car CD Player",
"Car DVD Changers",
"Car DVD Players",
"Car GPS",
"Car Monitors",
"Car Speakers",
"Card Readers",
"Carts",
"Cash Registers",
"Cat 5 Cables",
"Cat 5e Cables",
"Cat 6 Cables",
"Cat 6a Cables",
"Cat 7 Cables",
"Cat 8 Cables",
"CD / DVD / Blu-ray Duplicators",
"CD Decks",
"CD Drives",
"CD Media",
"CD/DVD Authoring",
"CD/DVD Printers",
"CD/DVD Wallets",
"CDMA Phones",
"CE Tablets",
"Cellular Phone Accessories",
"Cellular Phone Batteries & Power Adapters",
"Cellular Phone Cables",
"Cellular Phone Cases & Holsters",
"Cellular Phone Prepaid Cards",
"Cellular Phone Screen Protectors",
"Central Speakers",
"CF Cards",
"Chartplotters",
"Chromebooks",
"Cleaning Accessories",
"Cleaning Media",
"Clusters",
"Coaxial Cables",
"Coin Counters",
"Color Laser Printers",
"Color Multifunction Laser Printers",       
"Communication Equipment Books & Manuals",
"Compact AV Systems",
"Compact Film Cameras",
"Computer / Math / Logic",
"Computer Based Training",
"Computer Coolers",
"Computer Fans",
"Computer Hardware Books & Manuals",
"Computer Speakers",
"Conference Microphones",
"Conference Phones",
"Consumer Video Adapters",
"Converters",
"Convertible Notebooks",
"Copiers",
"Copper Transceivers",
"Corded Keyboards",
"Counterfeit Detectors",
"Creativity Software Books & Manuals",
"CRM Software",
"Crossover Cables",
"CRT Monitors",
"CRT TVs",
"Cutters & Trimmers",
"D-AMPS & Analog Cellular Phones",
"Darkroom Accessories",
"Data Analysis & Content Management",
"Data Cartridge Drives",
"Data Collection Terminals",
"Databases & Tools",
"DDR DIMM",
"DDR SO-DIMM ",
"DDR2 DIMM",
"DDR2 SO-DIMM",
"DDR3 DIMM",
"DDR3 SO-DIMM",
"DDR4 DIMM",
"DDR4 SO-DIMM",
"DDR5 DIMM",
"DDR5 SO-DIMM",
"Desktop Accessories",
"Desktop Memory",
"Desktop Publishing",
"Desktop Replacement Notebooks",
"Developer Tools",
"Developing & Processing Equipment",
"Development Tools",
"Dial-Up Modems",
"Digital Camera Lenses",
"Digital Cameras For Kids",
"Digital Projectors",
"Digital Signage Displays",
"Digital Signage Players",
"Digital Voice Recorders",
"DisplayPort Video Adapters",
"DLP Projectors",
"Docking Cradles",
"Document Cameras",
"Document Management Software",
"Document Scanners",
"DOS",
"Dot-Matrix Printers",
"DRAM",
"DSL Modems",
"DVD / HDD Combos",
"DVD / TV Combos",
"DVD Camcorders",
"DVD Changers",
"DVD Decks",
"DVD Drives",
"DVD Media",
"DVD Recorders",
"DVD/VCR Combos",
"DVI Video Adapters",
"DVRs",
"E-commerce Software",
"Earbud & In-Ear Headphones",
"Early Learning",
"eBook Readers",
"eCommerce Solutions",
"Education & Reference",
"Education Software Books & Manuals",
"Email Software",
"Encyclopedia",
"Enlargers & Components",
"Enterprise Bridges & Routers",
"Entertainment Software Books & Manuals",
"EPS Power Supplies",
"Equalizers",
"Ergonomic Keyboards",
"Ethernet Disk Arrays",
"Ethernet Print Servers",
"Extended ATX Cases",
"External Hard Drives",
"External Solid State Drives",
"External Sound Cards",
"External Tape Drives",
"Fanless Coolers & Heatsinks",
"Fax Machines",
"Fax Software",
"Fiber Network Adapters",
"Fibre Channel Disk Arrays",
"File Managers",
"File Transfer",
"Films",
"Finance / Tax Preparation",
"Firewall / VPN Appliances",
"FireWire Adapters",
"FireWire Cables",
"FireWire Disk Arrays",
"Fishfinders",
"Fixed Cellular Phones",
"Flash Duplicators",
"Flashes",
"Flatbed Scanners",
"Floppy Drives",
"FM Transceivers",
"Fonts & Font Tools",
"Foreign Languages & Translation",
"Game Utilities",
"Gamepads",
"Gamer Clothing",
"Gaming Desktops",
"Gaming Keyboards",
"Gaming Notebooks",
"GBIC Transceivers",
"Gigabit Hubs & Switches",
"Gigabit Network Adapters",
"GIS & Map Creation Software",
"GPS Accessories",
"GPS Antennas",
"GPS Cables",
"GPS For Aviation",
"GPS For Cycling",
"GPS For Hiking",
"GPS For Running",
"GPS Modules",
"GPS Power Adapters & Batteries",
"GPS Software",
"GPS Watches",
"Graphic Tablet & Whiteboard Accessories",
"Graphic Tablets & Whiteboards",
"Graphics & Photo Editing",
"Graphics & Publishing Software",
"Groupware",
"GSM Phones",
"Handheld Accessories",
"Handheld Computers",
"Hard Drive Enclosures",
"HD DVD Players",
"HDD Camcorders",
"HDD Duplicators",
"HDMI Cables",
"HDMI Video Adapters",
"HDV Camcorders",
"Headphones Accessories",
"Headphones Cables",
"Headphones Carrying Cases",
"HelpDesk & Inventory Systems",
"High Definition Camcorders",
"Home / Lifestyle Software Books & Manuals",
"Home & Hobbies",
"Home Audio Accessories",
"Home Media Players",
"Hotel & Hospitality TVs & Displays",
"HSE management",
"Human Resources",
"ID Card Printers",
"IDE Cables",
"iDEN Phones",
"InfiniBand Switches",
"Ink-Jet Printers",
"Instant Communication Software",
"Intel Desktops",
"Intel Notebooks",
"Intel Processors",
"Interactive Whiteboards",
"Internal Hard Drives",
"Internal Solid State Drives",
"Internal Sound Cards",
"Internal Tape Drives",
"Internet - E-Commerce Books & Manuals",
"Internet - Web Design / Publishing Books & Manuals",
"Internet / Communication Software Books & Manuals",
"Internet Utilities",
"Intrusion Detection / Prevention",
"IP Telephony",
"IP TV",
"iPhone",
"iPod Accessories",
"iPod Speakers",
"iPods",
"iSCSI Disk Arrays",
"Joysticks",
"Keyboard & Mouse Accessories",
"Keyboard & Mouse Bundles",
"Keyboard & Mouse Cables",
"Keyboard Accessories",
"Kiosks",
"KVM Accessories",
"KVM Cables",
"KVM Console",
"KVM Over IP",
"Label Printers",
"Labeling / Barcode Software",
"Laminators",
"Large Format Camera Lenses",
"Large Format Display Accessories",
"Large-Format Printers",
"Laser Projectors",
"LCD Monitors",
"LCD Projectors",
"LCD TVs",
"LCD/LED Large Format Displays",
"LCOS Projectors",
"Learning Management",
"LED Monitors",
"LED TVs",
"Legacy Cables",
"Legacy Controller Cards",
"Legacy Recording Media",
"Lens Converters & Adapters",
"Light Control",
"Light Meters",
"Lighting Filters",
"Lightning Cables",
"Linux",
"Linux Software",
"Liquid Cooling Systems",
"LNB",
"Long Range Two-Way Radios",
"Long-Zoom Compact Cameras",
"Mac Hardware Books & Manuals",
"Mac Software Books & Manuals",
"MacOS Licenses & Media",
"Magneto-Optical Drives",
"Managed Switches",
"Management Books",
"Map/Atlas/Travel",
"Marine Accessories",
"Marine Cables",
"Marine GPS",
"Medical Displays",
"Medical Keyboards & Mice",
"Medium Camera Lenses",
"Micro ATX Cases",
"Micro-SD Cards",
"Microcassette Recorders",
"Mini ITX Cases",
"Mini-DV Camcorders",
"Mirrorless System Digital Cameras",
"MLC Solid State Drives",
"Mobile Device Management",
"Mobile Device Synchronization",
"Mobile Workstations",
"Modem Accessories",
"Modem Cables",
"Monitor Cables",
"Monitor Stands & Mounts",
"Monochrome Laser Printers",
"Motherboards (for AMD Processors)",
"Motherboards (for Intel Processors)",
"Motion Sensors",
"Motorcycle GPS",
"Mountable Projectors",
"Mounts",
"Mouse Accessories",
"Movies & TV Shows",
"MP3 Players",
"Multi-Purpose Bags",
"Multifunction Ink-Jet Printers",
"Multifunction Page Wide Array Printers",
"Multifunction Supertank Printers",
"Multimedia Players",
"Multimode Fiber Cables",
"Multiplexers",
"Music",
"NAS",
"Natural Sciences",
"Netbooks",
"Network & Enterprise Management",
"Network Antennas & Accessories",
"Network Appliance Software",
"Network Audio Components",
"Network Cabling Accessories",
"Network Cameras",
"Network Hubs",
"Network Security Appliances",
"Network Security Books & Manuals",
"Network Security Software",
"Network Software",
"Network Utilities",
"Networking Hardware Books & Manuals",
"Networking Memory",
"Networking Software Books & Manuals",
"Notebook Batteries",
"Notebook Docking Stations",
"Notebook Hard Drives",
"Notebook Power Adapters/Chargers",
"Numeric Keypads",
"NVIDIA Video Cards",
"OCR Software",
"Office Application Suites",
"Office Software",
"OLED TVs",
"Operating System Books & Manuals",
"Optical Cables",
"Optical Transceivers",
"OS Suites",
"Outdoor Speakers",
"Outdoor TVs",
"Output Accessories",
"Over-Ear & On-Ear Headphones",
"Overhead Projector Supplies",
"Overhead Projectors",
"Page Wide Array Printers",
"Parallel Cables",
"Patch Cables",
"Patch Panels",
"PBX Phones & Systems",
"PC Card Network Adapters",
"PC Maintenance",
"PC Media Centers",
"PCI Network Adapters",
"PCI-E Network Adapters",
"PCI-X Network Adapters",
"Personal Messengers",
"Phone Accessories",
"Phone/Modem Cables",
"Photo / Video / Sound Libraries",
"Photo / Video Books & Manuals",
"Photo Albums",
"Photo Art Books & Manuals",
"Photo Enlarging Paper",
"Photo Frames",
"Photo Printers",
"Photo Storage",
"Photographic Chemistry",
"Picture Books",
"Plasma Panels",
"Plasma TVs",
"Point Of Sale Computers",
"Policy Management",
"Portable Cassette Players & Recorders",
"Portable CD Players",
"Portable DVD & Blu-ray Players",
"Portable DVD Players",
"Portable MD Players",
"Portable Media Players",
"Portable Player Accessories",
"Portable Player Cables",
"Portable Player Carrying Cases",
"Portable Player Power",
"Portable Radios",
"Portable Speakers",
"Portable TVs",
"POS Machine Accessories",
"POS Monitors",
"POS Receipt Printers",
"Power Accessories",
"Power Adapters & Chargers",
"Power Cables",
"Power Enclosures",
"Power Over Ethernet Wireless",
"Presentation",
"Print Management",
"Printer Cables",
"Printer Memory",
"Privacy Filters",
"Productivity Software Books & Manuals",
"Professional Camcorders",
"Professional Video Adapters",
"Programming Languages",
"Programming Tools Books & Manuals",
"Project Management",
"Projection Screens",
"Projector Accessories",
"Projector Mounts",
"Projector Trolleys & Stands",
"Public Address Speakers",
"Quad Processors & Video Multiplexers",
"Rack Servers",
"Rack-Mountable Hubs & Switches",
"Rack-Mountable UPS",
"Radio Scanners",
"Radio Tuners",
"Rangefinder Film Cameras",
"RDRAM",
"RDX Media",
"Rear-Projection TVs",
"Recovery / Backup Software",
"Religion",
"Remote Access Software",
"Remote Controls",
"Retail MacOS",
"Retail Windows",
"Right / Left Channel Speakers",
"RISC Servers",
"Rugged Notebooks",
"SAN",
"SAS Cables",
"SATA Cables",
"SATA Disk Arrays",
"Satellite & Cable TV Accessories",
"Satellite Car Radio",
"Satellite Dishes",
"Satellite Radio",
"Satellite Receivers",
"Satellite Receivers With HDD",
"Satellite TV Systems",
"Scan Management",
"Scanner Accessories",
"Scanner Power",
"Schedule & Contact Management",
"Screen Protectors",
"SCSI / IDE / Floppy Cables",
"SCSI Cables",
"SCSI Disk Arrays",
"SD Cards",
"SDRAM",
"Security & Privacy Filters",
"Security Cables & Locks",
"Security Cameras",
"Security Chips, Tokens & Smart Cards",
"Security DVRs",
"Serial ATA Cables",
"Serial Cables",
"Server Accessories",
"Server Hard Drives",
"Server Memory",
"Server/Workstation Motherboards",
"SFP Transceivers",
"SFX Power Supplies",
"Sheetfed Scanners",
"Short Range Two-Way Radios",
"Short-Throw Projectors",
"Shredders",
"Signal Extenders",
"Single-board Computers",
"Singlemode Fiber Cables",
"SLC Solid State Drives",
"Slide / Film Scanners",
"SLR Digital Cameras",
"SLR Film Cameras",
"Smart Glasses",
"Smart Tracking",
"Smart Watch Accessories",
"Smart Watches",
"SmartCard Readers",
"Software Suites",
"SOHO Bridges & Routers",
"SOHO Hubs & Switches",
"Sound Bars",
"Sound Editing & Recording",
"Spare Parts",
"Speaker Accessories",
"Speaker Cables",
"Speaker Support Hardware",
"Speakerphones",
"Special Network Cables",
"Special Scanners",
"Specialized Network Devices",
"Specialty Film Cameras",
"Specific Cables",
"Specific Cases",
"Spreadsheets",
"Stand-Alone UPS",
"Stands",
"Stands for Notebooks & Tablets",
"Stationary DVD Players",
"Studio Light",
"Studio Mounting",
"Subwoofers",
"Supertank Printers",
"Surge Suppressors & PDUs",
"Surround Speakers",
"Switch Expansion Modules",
"System Deployment & Migration Software",
"Tablet Carrying Cases",
"Tablet Computers",
"Tablet PCs",
"Tape Automation",
"Tape Decks",
"Telephone Accessories",
"Thermal Printers",
"Thin Client Notebooks",
"Thin Clients",
"Thunderbolt Disk Arrays",
"Time Lapse VCR",
"Tools & Tool Kits",
"Touchscreen Monitors",
"Tower Servers",
"Traffic Balancers & Optimizers",
"True Wireless Earbuds",
"Turntable Accessories",
"Turntables",
"TV & Radio Antennas",
"TV accessories",
"Ultra Thin Notebooks",
"Ultra-Light Notebooks",
"Ultra-Mobile PCs",
"Ultrabooks",
"Underwater Digital Cameras",
"Underwater Film Cameras",
"Unix",
"Unix Software",
"Unmanaged Switches",
"Upconverting DVD Players",
"UPS Batteries",
"Upscaling DVD Players",
"USB Cables",
"USB Controllers",
"USB Disk Arrays",
"USB Hubs",
"USB Network Adapters",
"Utilities",
"Utilities Software Books & Manuals",
"Utilities Suites",
"Video & Audio Conferencing",
"Video Cables",
"Video Capture Cards",
"Video Controller Memory Upgrades",
"Video Converters",
"Video Editing",
"Video Editing Controllers, Mixers & Titlers",
"Video Games & Gadgets",
"Video Servers",
"Video Surveillance Accessories",
"Video Surveillance Solutions",
"Virtual Reality Cameras",
"Virtualization Software",
"Voice / Data Modules",
"Voice Recognition / Text-to-Speech",
"VoIP Gateways",
"VoIP Modules",
"VoIP Phones",
"VoIP Routers",
"VoIP Software",
"VR Headsets for Smartphones",
"Watch Phones",
"Web Cameras",
"Web Conferencing Software",
"Web Design / Publishing",
"Web Development",
"Wheels & Pedals",
"Windows Licenses & Media",
"Windows To Go drives",
"Wired Headphones",
"Wired Network Adapters",
"Wired Telephones",
"Wireless Access Points",
"Wireless Audio & Video Sharing",
"Wireless Bridges",
"Wireless Controllers",
"Wireless Headphones",
"Wireless IP Cameras",
"Wireless Keyboards",
"Wireless Network Adapters",
"Wireless NICs",
"Wireless Print Servers",
"Wireless Routers",
"Wireless Telephones",
"Word Processing",
"Workstation Blade",
"x86 Blade Servers",
"x86 Rack Servers",
"x86 Tower Servers",
"XD Cards",
"10/100 Network Adapters",
"AMD Processors",
"Anti-Spam",
"Anti-Spyware",
"Antivirus & Security Software",
"ATX Power Supplies",
"Authentication Software",
"Backpacks",
"Blu-ray Drives",
"Bluetooth Mice",
"Briefcases",
"Brother Ink Cartridges",
"Brother Toner Cartridges",
"Calculator Accessories",
"Canon Ink Cartridges",
"Canon Toner Cartridges",
"Cash Drawers",
"Cellular Modems",
"Computerized Time Clock Systems",
"Corded Mice",
"Dell Ink Cartridges",
"Dell Toner Cartridges",
"Desktop Calculators",
"Electronic Dictionaries",
"Electronic Organizers",
"Encryption Software",
"Epson Ink Cartridges",
"Epson Toner Cartridges",
"Financial Calculators",
"Firewalls",
"Flash Memory Camcorders",
"Gaming Mice",
"Graphing Calculators",
"Hard Drive Mounting",
"HP Ink Cartridges",
"HP Toner Cartridges",
"Internet Filtering Software",
"Intrusion Detection/Prevention",
"ISDN Modems",
"Kodak Ink Cartridges",
"Konica Minolta Toner Cartridges",
"KVM Switches",
"Leather Carrying Cases",
"Lexmark Ink Cartridges",
"Lexmark Toner Cartridges",
"Messenger Bags",
"Modem / NIC Combos",
"Notebook Memory",
"Notebook Mice",
"Notebook Sleeves",
"OKI Toner Cartridges",
"Other Ink Cartridges",
"Other Toner Cartridges",
"Panasonic Toner Cartridges",
"Pocket Calculators",
"Pocket Projectors",
"Power Banks",
"Printing Calculators",
"Projector Cables",
"Projector Lamps",
"Projector Power",
"Projector Screens",
"Samsung Ink Cartridges",
"Samsung Toner Cartridges",
"SAS Disk Arrays",
"Scientific Calculators",
"Security Cabinets",
"Security Suites",
"Sharp Ink Cartridges",
"Sharp Toner Cartridges",
"Standalone Time Clock Machines",
"Styli",
"Tape Media",
"Time Clock Machines Accessories",
"Touchscreen Large Format Displays",
"Typewriter Accessories",
"Typewriters",
"Video Surveillance Software",
"VPN Software",
"VR Headsets",
"Wheeled Cases",
"Wired IP Cameras",
"Wireless Mice",
"karangroup2",
"karansubgroup1",
"Mini Tablet",
"Large tablet",
"6 Tablet",
"subgroup1",
"subgroup2",
"super subgroup1",
"super subgroup2",
"subgroup7",
"subgroup5",
"Techgroup 3",
"Tech group 3",
"Test Tech Group 1",
"Legal",
"News",
"Distributed Storage (CDN)",
"Design and Development",
"Testing",
"Service Desk",
"IT Service Management",
"Business Continuity and Disaster Recovery",
"Data Management",
"Data Warehouse",
"Machine Learning",
"Artificial Intelligence",
"Streaming",
"Test Group",
"Application Gateway Standard v2",
"Azure Active Directory B2X",
"Azure App Service Basic Plan",
"Azure App Service Basic Plan - Linux",
"Azure App Service Free Plan",
"Azure App Service Free Plan - Linux",
"Azure App Service Premium v3 Plan - Linux",
"Azure Bastion",
"Azure DNS",
"Azure Monitor",
"Backup",
"Bandwidth Inter-Region",
"Blob Storage",
"Files",
"Fortinet FortiGate Next-Generation Firewall (VM)",
"Functions",
"General Block Blob",
"General Block Blob v2",
"IoT Hub",
"IoT Hub Device Provisioning",
"IP Addresses",
"Key Vault",
"Load Balancer",
"Log Analytics",
"Logic Apps",
"Microsoft Defender CSPM",
"Microsoft Defender for Resource Manager",
"Microsoft Defender for Servers",
"Network Watcher",
"Premium SSD Managed Disks",
"Process Automation",
"Queues",
"Queues v2",
"Rtn Preference: MGN",
"Service Bus",
"SQL Database Single Standard",
"SQL Database Single/Elastic Pool General Purpose - Compute Gen5",
"SQL Database Single/Elastic Pool General Purpose - SQL License",
"SQL Database Single/Elastic Pool General Purpose - Storage",
"SQL Server Express Edition",
"Standard HDD Managed Disks",
"Standard Page Blob",
"Standard Page Blob v2",
"Standard SSD Managed Disks",
"Storage - Bandwidth",
"Tables",
"Ubuntu 24.04",
"Virtual Machines BS Series",
"Virtual Machines BS Series Windows",
"Virtual Machines Dav4 Series Windows",
"Virtual Machines DCSv2 Series",
"Virtual Machines DCSv2 Series Windows",
"Virtual Machines Ddsv5 Series Windows",
"Virtual Machines Dlsv5 Series",
"Virtual Machines Dsv4 Series",
"Virtual Machines Dv2 Series",
"Virtual Machines Dv2 Series Windows",
"Virtual Machines Dv3 Series",
"Virtual Machines Dv3 Series Windows",
"Virtual Machines F Series Windows",
"Virtual Machines FSv2 Series",
"Virtual Machines FSv2 Series Windows",
"Virtual Network Private Link",
"Cloud VPN Gateway",
"Zabbix Proxy 6.4",
"Zabbix Server 6.4",
"AWS Backup",
"Amazon EC2 Container Registry (ECR)",
"Amazon Elastic Compute Cloud - Compute",
"Amazon Elastic Container Service",
"Amazon Elastic Container Service for Kubernetes",
"Amazon Elastic File System",
"Amazon Elastic Load Balancing",
"Amazon ElastiCache",
"Amazon GuardDuty",
"Amazon Macie",
"Amazon Managed Service for Prometheus",
"Amazon OpenSearch Service",
"Amazon Pinpoint",
"Amazon Relational Database Service",
"Amazon Simple Email Service",
"Amazon Simple Notification Service",
"Amazon Simple Queue Service",
"Amazon Simple Storage Service",
"Amazon Virtual Private Cloud",
"Amazon WorkDocs",
"Amazon WorkSpaces",
"AmazonCloudWatch",
"AWS CloudFormation",
"AWS CloudTrail",
"AWS Config",
"AWS Cost Explorer",
"AWS Glue",
"AWS Key Management Service",
"AWS Lambda",
"AWS Secrets Manager",
"AWS Security Hub",
"AWS Step Functions",
"AWS Support (Business)",
"AWS Systems Manager",
"AWS X-Ray",
"CloudWatch Events",
"EC2 - Other",
"Keycloak with MySQL on Ubuntu 20.04 LTS by Neodoo",
"Pinecone Vector Database - Pay As You Go Pricing",
"Tax",
"Pinecone - Pay As You Go",
"Amazon Elastic CDDDD"
]

TECH_TYPES = [ "Hardware", "License", "Subscription", "Maintenance", "Virtual Machines", "Freeware", "Certificate" ]

# Load failed asset data
with open("failed_assets_fixed.json", "r") as f:
    data = json.load(f)

# Iterate through assets
for i, asset in enumerate(data, start=1):
    # Safely get fields
    model = asset.get("MODEL", "")
    manufacturer = asset.get("MANUFACTURER", "")
    metadata_dict = asset.get("metadata", {})

    # Pretty-print metadata
    try:
        metadata = json.dumps(metadata_dict, indent=4)
    except (TypeError, ValueError):
        metadata = str(metadata_dict)  # fallback if metadata is not valid JSON

    # Build the prompt
    prompt = f"""
    
    The data provided is of an asset which we were unable to match or identify.
    
    This is the data we received:
        Model: {model}
        Manufacturer: {manufacturer}
        Metadata: {metadata}

    Using this data help to find the exact model. 
    
    If you are unable to find the exact model find the closest results.

    Return these pieces of data

    Brand/Manufacturer/Vendor: (e.g. Apple or ASUS)
    Brand Country: 
    Brand Domain: (e.g. https://www.asus.com/ or https://www.apple.com/)
    Tech Type: Fill this field using this list: {TECH_TYPES}
    Tech Group: Fill this field using this list: {TECH_GROUPS}
    
    Product SKU/ID: 
    Product Description: 
    Product Features: Only list 5 features (e.g., RAM, CPU, Display, Refresh Rate, etc.)

    """

    # There is no charge or quota restriction for using the CountTokens API. 
    # The maximum quota for the CountTokens API is 3000 requests per minute.
    # https://docs.cloud.google.com/vertex-ai/generative-ai/docs/multimodal/get-token-count
    
    token_info = client.models.count_tokens(
        model="gemini-2.5-flash",  
        contents=prompt
    )
    
    total_tokens = token_info.total_tokens  

    if total_tokens < ideal_tokens_per_request:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=(prompt),
            config=config,
        )

        final_result = add_citations_at_end(response)

        # Debugging print statements
        print(f"\n--- Result for Asset #{i} ---\n{final_result}\n")
        print(f"Total Tokens in Prompt: {total_tokens}/{ideal_tokens_per_request}")
        print("=" * 100)

        # Since there is 10 requests per minute, we can pass about 60 / 10 = 1 request every 6 seconds
        time.sleep(6) 

    else:
        print("Prompt is too large skipping asset.")
        continue
